quarkus:
  datasource:
    db-kind: postgresql
    username: user
    password: password
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/krilldb
      max-size: 16
  http:
    cors:
      ~: true
      methods: 'GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD'
#  hibernate-orm:
#    database:
#      generation: drop-and-create
#    log:
#      sql: true
  liquibase:
    migrate-at-start: true
  container-image:
    registry: ${ECR_REGISTRY:}
    group: ${ECR_GROUP:}
    name: ${ECR_REPOSITORY:krill-backend}
    tag: ${IMAGE_TAG:}
  smallrye-openapi:
    path: /openapi
  swagger-ui:
    always-include: true
    path: /swagger-ui
  log:
    level: INFO
    file:
      enable: true