on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true

name: Push to ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.REGISTRY_NAME }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          ECR_GROUP: ${{ secrets.GROUP_NAME }}
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          # Build a docker container and push it to ECR
          echo "Build and push"
          ./mvnw package -Dquarkus.container-image.build=true
          docker push $ECR_REGISTRY/$ECR_GROUP/$ECR_REPOSITORY:$IMAGE_TAG